-- Booking schema DDL: rooms, room_availability, customers, bookings, and
-- booking_rooms. Executed as one statement by
-- `blue_horizon.load_data.booking_pgsql.setup_schema`, which fills in this
-- file's four `CREATE TYPE ... AS ENUM` placeholders below with the enum
-- labels read from the source data (see `build_enum_definition`). Note for
-- anyone editing this file: every curly-braced name below is a live
-- substitution target, including inside comments -- `setup_schema` runs the
-- whole file through `psycopg.sql.SQL(...).format()`, which does not
-- distinguish SQL from comment text, so a stray curly-braced word anywhere
-- in this file must exactly name one of `setup_schema`'s keyword arguments,
-- or the substitution fails outright.
--
-- Every table here is dropped and recreated with CASCADE, which is what
-- makes a full reload possible. That also drops any grants on it, which is
-- why `reload_sql_tables` reapplies them afterward, via
-- `regrant_booking_agent_role`.
--
-- The maintenance-booking-guard trigger is deliberately NOT in this file --
-- see `maintenance_booking_guard.sql` for why it is installed separately,
-- later in `reload_sql_tables`.

-- --- rooms ---------------------------------------------------------------

DROP TABLE IF EXISTS rooms CASCADE;
DROP TYPE IF EXISTS room_type CASCADE;
DROP TYPE IF EXISTS room_bed_type CASCADE;
DROP TYPE IF EXISTS room_status_type CASCADE;

CREATE TYPE room_type AS ENUM {room_type_values};
CREATE TYPE room_bed_type AS ENUM {bed_type_values};
CREATE TYPE room_status_type AS ENUM {room_status_values};

CREATE TABLE rooms (
    room_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_number INT NOT NULL,
    floor INT NOT NULL,
    type room_type,
    square_feet INT,
    basic_amenities TEXT[],
    additional_amenities TEXT[],
    max_occupancy INT,
    bed_type room_bed_type,
    view_type TEXT[],
    accessibility BOOLEAN,
    status room_status_type,
    last_renovation DATE,
    base_rate NUMERIC(10, 2),
    max_rate NUMERIC(10, 2)
);

-- --- room_availability -----------------------------------------------------

DROP TABLE IF EXISTS room_availability;
DROP TYPE IF EXISTS availability_status_type CASCADE;

CREATE TYPE availability_status_type AS ENUM {availability_status_values};

CREATE TABLE room_availability (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id INT NOT NULL,
    room_number INT NOT NULL,
    date DATE NOT NULL,
    status availability_status_type,
    price NUMERIC(8,2),
    max_occupancy INT,
    FOREIGN KEY (room_id) REFERENCES rooms(room_id),
    CONSTRAINT room_availability_room_id_date_uniq UNIQUE (room_id, date)
);

-- --- customers -------------------------------------------------------------

DROP TABLE IF EXISTS customers CASCADE;

CREATE TABLE customers (
    customer_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(32) NOT NULL,
    last_name VARCHAR(32) NOT NULL
);

-- --- bookings ----------------------------------------------------------------

DROP TABLE IF EXISTS bookings CASCADE;
DROP TYPE IF EXISTS booking_status CASCADE;

CREATE TYPE booking_status AS ENUM (
    'confirmed', 'checked_in', 'checked_out', 'cancelled'
);

CREATE TABLE bookings (
    booking_id    BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    customer_id   INT NOT NULL REFERENCES customers(customer_id) ON DELETE RESTRICT,
    status        booking_status NOT NULL DEFAULT 'confirmed',
    booked_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    cancelled_at  TIMESTAMPTZ,
    confirmation_number VARCHAR(16) UNIQUE,
    CONSTRAINT cancel_coherent CHECK ((status = 'cancelled') = (cancelled_at IS NOT NULL))
);

-- --- booking_rooms ---------------------------------------------------------
--
-- Carries a GiST exclusion constraint, `booking_rooms_no_overlap`, that
-- makes two rows for the same `room_id` with overlapping
-- `[check_in, check_out)` spans impossible to insert or update into
-- existence -- the database itself refuses a double-booking, rather than
-- relying solely on `write_ops`'s `FOR UPDATE` locking on
-- `room_availability` to prevent one. The half-open range means one stay's
-- `check_out` equalling another's `check_in` (same-day turnover) does not
-- count as an overlap. Requires the `btree_gist` extension (created by
-- `reload_sql_tables` before this script runs) for GiST to support `=` on
-- the integer `room_id` column alongside the range overlap operator.

DROP TABLE IF EXISTS booking_rooms CASCADE;

CREATE TABLE booking_rooms (
    booking_room_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    booking_id      BIGINT NOT NULL REFERENCES bookings(booking_id) ON DELETE RESTRICT,
    room_id         INT    NOT NULL REFERENCES rooms(room_id),
    check_in        DATE   NOT NULL,
    check_out       DATE   NOT NULL,
    total_amount    NUMERIC(10,2) NOT NULL,
    CHECK (check_out > check_in),
    CONSTRAINT booking_rooms_no_overlap EXCLUDE USING gist (
        room_id WITH =,
        daterange(check_in, check_out, '[)') WITH &&
    )
);
