import os
from functools import lru_cache
from pathlib import Path
from string import Template

import psycopg
from dotenv import load_dotenv
from langchain.agents import create_agent
from langchain_community.agent_toolkits import SQLDatabaseToolkit
from langchain_community.utilities import SQLDatabase
from langchain_openai import ChatOpenAI
from langgraph.graph.state import CompiledStateGraph

load_dotenv()
neon_conn_string = os.getenv("NEON_DB_URL")
langchain_neon_conn_string = neon_conn_string.replace("postgresql", "postgresql+psycopg")

gpt_model = "gpt-5-mini"

prompt_fname="sql_prompt.txt"

enums = ["availability_status_type", "room_bed_type", "room_status_type", "room_type"]
enum_values = {}

with psycopg.connect(neon_conn_string) as neon_conn:
    with neon_conn.cursor() as cur:
        for enum in enums:
            cur.execute(f"SELECT enum_range(NULL::{enum})")
            enum_values[enum] = [val.strip('\'"{}') for val in cur.fetchall()[0][0].split(',')]
        cur.execute("SELECT DISTINCT unnest(basic_amenities) FROM rooms;")
        basic_amenities = [val[0] for val in cur.fetchall()]
        cur.execute("SELECT DISTINCT unnest(additional_amenities) FROM rooms;")
        additional_amenities = [val[0] for val in cur.fetchall()]
        cur.execute("SELECT DISTINCT unnest(view_type) FROM rooms;")
        view_types = [val[0] for val in cur.fetchall()]

schema_description = {
    "rooms": (f"""
            CREATE TABLE rooms (
                room_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Do not return
                room_number INT NOT NULL,
                floor INT NOT NULL,
                type room_type, -- Enum with options {enum_values['room_type']}
                square_feet INT,
                basic_amenities TEXT[],  -- Options are {basic_amenities}
                additional_amenities TEXT[], -- Options are {additional_amenities}
                max_occupancy INT,
                bed_type room_bed_type,  -- Enum with options {enum_values['room_bed_type']}
                view_type TEXT[],  -- Options are {view_types}
                accessibility BOOLEAN,  -- Whether handicapped accessible
                status room_status_type, -- Enum with options {enum_values['room_status_type']}, do not return
                last_renovation DATE, -- Do not provide unless asked for
                base_rate NUMERIC(10, 2),  -- Do not provide unless asked for
                max_rate NUMERIC(10, 2)  -- Do not provide unless asked for
                -- The table lists details about all the rooms in the hotel.
            );
    """),
    "room_availability": (f"""
            CREATE TABLE room_availability (
                id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Do not return
                room_id INT NOT NULL, -- Do not return
                room_number INT NOT NULL,
                date DATE NOT NULL,
                status availability_status_type,  -- Enum with options {enum_values['availability_status_type']}
                price NUMERIC(8,2),
                max_occupancy INT,
                FOREIGN KEY (room_id) REFERENCES rooms(room_id),
                CONSTRAINT room_availability_room_id_date_uniq UNIQUE (room_id, date)
                -- The table lists the room availability by date and the corresponding rate
            );
    """),
}

db = SQLDatabase.from_uri(database_uri=langchain_neon_conn_string, include_tables=schema_description.keys(), custom_table_info=schema_description)
llm = ChatOpenAI(model=gpt_model, temperature=0, reasoning={"effort": "low"})
sql_toolkit = SQLDatabaseToolkit(db=db, llm=llm)


dialect="PostgreSQL"
top_k=4


def resolve_prompts_dir(*, prompts_folder: str = "../system_prompts") -> Path:
    """Resolve the prompts directory.

    Assumes prompts live in a single folder next to this module.

    Args:
        prompts_folder: Folder name.

    Returns:
        Path: Resolved prompts directory.

    Raises:
        RuntimeError: If the directory does not exist.
    """
    prompts_dir = (Path(__file__).parent / prompts_folder).resolve()
    if not prompts_dir.exists() or not prompts_dir.is_dir():
        msg = f"Prompts folder not found: {prompts_dir}"
        raise RuntimeError(msg)
    return prompts_dir


def resolve_system_prompt_path(*, filename: str, prompts_dir: Path) -> Path:
    """Resolve a prompt template file within the prompts directory.

    Args:
        filename: Prompt file name (no path).
        prompts_dir: Directory that contains all prompt files.

    Returns:
        Path: Resolved path to the prompt file.

    Raises:
        RuntimeError: If the file does not exist.
    """
    candidate = (prompts_dir / filename).resolve()
    if not candidate.exists() or not candidate.is_file():
        msg = f"System prompt template not found: {candidate}"
        raise RuntimeError(msg)
    return candidate

prompts_dir = resolve_prompts_dir()
sql_prompt_path = resolve_system_prompt_path(prompts_dir=prompts_dir,
                                             filename=prompt_fname)

@lru_cache(maxsize=5)
def _load_prompt_template(path: Path) -> Template:
    """Load and cache a prompt template from disk."""
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as exc:
        msg = f"Failed to read prompt template at: {path}"
        raise RuntimeError(msg) from exc
    return Template(text)


def build_system_prompt(*, top_k: int, dialect: str, enum_values: dict[str, list],
                        basic_amenities: list[str], additional_amenities: list[str],
                        view_types: list[str], prompt_path: Path) -> str:
    """Render the system prompt with runtime substitutions."""
    template = _load_prompt_template(prompt_path)
    return template.safe_substitute(top_k=top_k, dialect=dialect,
                                    room_type=enum_values["room_type"],
                                    basic_amenities=basic_amenities,
                                    additional_amenities=additional_amenities,
                                    room_bed_type=enum_values["room_bed_type"],
                                    view_types=view_types,
                                    room_status_type=enum_values["room_status_type"],
                                    availability_status_type=enum_values["availability_status_type"])

system_prompt = build_system_prompt(top_k=top_k, dialect=dialect,
                                    enum_values=enum_values,
                                    basic_amenities=basic_amenities,
                                    additional_amenities=additional_amenities,
                                    view_types=view_types,
                                    prompt_path=sql_prompt_path)

def get_rooms_agent() -> CompiledStateGraph:
    return create_agent(model=llm, tools=[sql_toolkit.get_tools()[0]], system_prompt=system_prompt)
