"""Streamlit chat UI for the Blue Horizon AI Concierge.

Provides a single-thread chat interface that communicates with the Blue Horizon
FastAPI backend via its REST API.

Run with:
    streamlit run ui/app.py

Environment variables:
    BLUE_HORIZON_API_URL: Base URL for the Blue Horizon API.
        Defaults to ``http://localhost:8000``.
    GOOGLE_CLIENT_ID: When set, enables Google OAuth authentication.
        Set alongside ``GOOGLE_CLIENT_SECRET`` as HuggingFace Space secrets.
        Access is controlled via Google Cloud Console's OAuth test users list.
"""

from __future__ import annotations

import dataclasses
import json
import logging
import os
import secrets
import threading
import uuid
from datetime import UTC, datetime, timedelta
from typing import TYPE_CHECKING, Any

import httpx2
import streamlit as st
from dotenv import load_dotenv

if TYPE_CHECKING:
    from streamlit.delta_generator import DeltaGenerator

load_dotenv()

# Named explicitly: under `streamlit run` this module is `__main__`, which
# would not identify the UI in a log shared with the API.
logger = logging.getLogger("ui.app")
_LOG_FORMAT = "%(asctime)s %(levelname)s %(name)s %(message)s"

_API_BASE: str = os.getenv("BLUE_HORIZON_API_URL", "http://127.0.0.1:8000").rstrip("/")
_AUTH_ENABLED: bool = bool(os.getenv("GOOGLE_CLIENT_ID"))
_CHAT_TIMEOUT_S: float = 90.0
_HEALTH_TIMEOUT_S: float = 3.0
# Real DB-backed reads (guest list, bookings), as opposed to the bare health
# ping above -- the booking pool opens connections on demand (min_size=0,
# see app_config.toml), so a request after any idle stretch can pay a Neon
# compute cold-start on top of the query itself.
_DATA_TIMEOUT_S: float = 20.0
_HTTP_OK: int = 200
_HTTP_FORBIDDEN: int = 403
_HTTP_NOT_FOUND: int = 404
_HTTP_CONFLICT: int = 409
_HTTP_SERVICE_UNAVAILABLE: int = 503
_HEALTH_POLL_ONLINE_INTERVAL_S: int = 30
_HEALTH_POLL_OFFLINE_INTERVAL_S: int = 5
# How long an assigned guest stays reserved for a session with no activity --
# covers both an idle-but-open tab and one that was simply closed, since a
# closed tab produces no further reruns to refresh the claim either way.
_GUEST_CLAIM_TTL_S: float = 600.0


# ============================
# Session state
# ============================


def _int_or_none(value: str | None) -> int | None:
    """Parse a query-param string as an int, tolerating anything malformed.

    Args:
        value: Raw query-param value, or ``None`` if the param was absent.

    Returns:
        int | None: The parsed integer, or ``None`` if ``value`` is ``None``
        or not a valid integer.

    """
    if value is None:
        return None
    try:
        return int(value)
    except ValueError:
        return None


def _init_session_state() -> None:
    """Initialise all required ``st.session_state`` keys on first run.

    Restores ``session_id`` and ``customer_id`` from the ``sid``/``cid`` URL
    query params when present, so a hard refresh reconnects to the same
    guest claim instead of burning a fresh one -- ``st.session_state``
    itself does not survive a refresh, but the URL does. `_render_guest_
    assignment()` still verifies the restored claim actually belongs to
    this session before trusting it. A fresh conversation thread ID and
    empty message history are created regardless: a refresh is meant to
    reset the conversation, just not the guest.
    """
    if "session_id" not in st.session_state:
        # Unlike thread_id, never regenerated by _reset_session(), since a
        # "New Conversation" click resets the chat thread, not who is
        # holding the guest claim.
        st.session_state.session_id = st.query_params.get("sid") or str(
            uuid.uuid4(),
        )
    if "thread_id" not in st.session_state:
        st.session_state.thread_id = str(uuid.uuid4())
    if "customer_id" not in st.session_state:
        st.session_state.customer_id = _int_or_none(st.query_params.get("cid"))
    if "messages" not in st.session_state:
        st.session_state.messages = []
    if "pending_proposal" not in st.session_state:
        st.session_state.pending_proposal = None
    if "pending_resend" not in st.session_state:
        # The guest's own text from a chat turn that failed to complete, so
        # "Send again" can replay it verbatim instead of asking them to
        # retype -- see ChatTurnResult and _render_pending_resend.
        st.session_state.pending_resend = None
    if "pending_resend_message" not in st.session_state:
        st.session_state.pending_resend_message = None
    if "api_online" not in st.session_state:
        # Refreshed by _render_sidebar() every rerun, before _render_chat()
        # reads it. The optimistic default only matters for the one render
        # that happens before _render_sidebar() has run once.
        st.session_state.api_online = True


def _reset_session() -> None:
    """Clear the conversation and start a new thread.

    Generates a fresh ``thread_id``, empties the message history, and
    dismisses any pending proposal -- a dialog from a conversation that no
    longer exists must not still be confirmable. Also drops any pending
    resend, since it holds text addressed to the conversation just ending.
    """
    _dismiss_pending_proposal()
    st.session_state.thread_id = str(uuid.uuid4())
    st.session_state.messages = []
    st.session_state.pending_resend = None
    st.session_state.pending_resend_message = None


# ============================
# API calls
# ============================


def _check_health() -> bool:
    """Poll the API health endpoint.

    Returns:
        ``True`` if the API responds with HTTP 200, ``False`` otherwise
        (including network errors and HTTP 503 while the agent is starting up).

    """
    try:
        response = httpx2.get(f"{_API_BASE}/v1/health", timeout=_HEALTH_TIMEOUT_S)
        return response.status_code == _HTTP_OK  # noqa: TRY300
    except Exception:  # noqa: BLE001
        return False


@st.cache_data(ttl=300, show_spinner=False)
def _fetch_customers_uncached() -> list[dict[str, Any]]:
    """Fetch the guest list backing automated guest assignment.

    Cached for five minutes: the seeded customer list never changes between
    a demo database reload. Streamlit only caches on a successful return, so
    a failed lookup (e.g. a cold booking-DB connection) is retried on the
    next call instead of being memoized as "no guests."

    Returns:
        list[dict[str, Any]]: `{customer_id, first_name, last_name}` per
        guest.

    Raises:
        httpx2.HTTPError: If the API could not be reached or returned an
            error status.

    """
    response = httpx2.get(f"{_API_BASE}/v1/customers", timeout=_DATA_TIMEOUT_S)
    response.raise_for_status()
    return response.json()


def _fetch_customers() -> list[dict[str, Any]]:
    """Fetch the guest list, logging and falling back to empty on failure.

    Returns:
        list[dict[str, Any]]: `{customer_id, first_name, last_name}` per
        guest, or an empty list if the API could not be reached.

    """
    try:
        return _fetch_customers_uncached()
    except Exception as exc:  # noqa: BLE001
        _log_api_failure(exc, "Could not fetch the guest list.")
        return []


def _fetch_bookings(customer_id: int) -> list[dict[str, Any]] | None:
    """Fetch one guest's bookings for the reservations panel.

    Args:
        customer_id: Guest whose bookings to fetch.

    Returns:
        list[dict[str, Any]] | None: Booking summaries, or ``None`` if the
        API could not be reached. Deliberately distinct from an empty list,
        which means the guest genuinely has no reservations -- collapsing
        the two would render a backend outage as "No reservations yet.".

    """
    try:
        response = httpx2.get(
            f"{_API_BASE}/v1/bookings",
            params={"customer_id": customer_id},
            timeout=_DATA_TIMEOUT_S,
        )
        response.raise_for_status()
        return response.json().get("bookings", [])
    except Exception as exc:  # noqa: BLE001
        _log_api_failure(
            exc, "Could not fetch bookings for customer_id=%s.", customer_id,
        )
        return None


def _log_api_failure(exc: BaseException, message: str, *args: object) -> None:
    """Log a failed API call, without a traceback when it is expected.

    A refused connection, a timeout, or an error status means the API is down
    or unhealthy, which the sidebar already reports, and its traceback runs
    to dozens of lines that say nothing ``exc`` itself does not. Those are
    logged as one warning line. Anything else, such as a malformed response
    body, is a defect and keeps its traceback.

    Args:
        exc: The exception the call raised.
        message: Log message format string.
        *args: Arguments for ``message``.

    """
    if isinstance(exc, httpx2.HTTPError):
        logger.warning(f"{message} %r", *args, exc)  # noqa: G004
        return
    logger.warning(message, *args, exc_info=exc)


@dataclasses.dataclass(frozen=True, slots=True)
class ConfirmOutcome:
    """Structured result of a `_confirm_proposal` call.

    Attributes:
        status: One of ``confirmed``, ``refused``, ``expired``,
            ``wrong_guest``, ``unavailable``, or ``unreachable``.
        message: Guest-facing text for this outcome, taken from the
            response body's ``detail``/``message`` where the server
            supplied one.
        keep_pending: Whether the confirmation dialog should stay open with
            Confirm still enabled. True only for ``unavailable`` and
            ``unreachable`` -- the two cases where the write was never
            evaluated (see `blue_horizon.agents.booking.proposals
            .ProposalStore.confirm`), so trying again is safe. Every other
            status is terminal.

    """

    status: str
    message: str
    keep_pending: bool


# Maps a non-2xx `/v1/booking/confirm` status code to its ConfirmOutcome
# status. Anything else (an unexpected 500, say) falls back to
# "unreachable" in `_confirm_proposal`: the safest assumption when the
# outcome is genuinely unknown is that it is still safe to try again,
# never that the guest already has the room.
_CONFIRM_STATUS_BY_HTTP_CODE: dict[int, str] = {
    _HTTP_NOT_FOUND: "expired",
    _HTTP_FORBIDDEN: "wrong_guest",
    _HTTP_CONFLICT: "refused",
    _HTTP_SERVICE_UNAVAILABLE: "unavailable",
}


def _response_field(response: httpx2.Response, field: str) -> str | None:
    """Best-effort extraction of one string field from a JSON response body.

    Args:
        response: An HTTP response that may or may not carry a JSON object
            body.
        field: The key to read (e.g. ``"detail"`` for a FastAPI
            ``HTTPException``, ``"message"`` for the ``/v1/chat`` readiness
            gate's own body shape).

    Returns:
        str | None: The field's string value, or ``None`` if the body was
        not JSON, was not an object, or the field was missing or not a
        string.

    """
    try:
        body = response.json()
    except ValueError:
        return None
    value = body.get(field) if isinstance(body, dict) else None
    return value if isinstance(value, str) else None


def _response_detail(response: httpx2.Response) -> str | None:
    """Best-effort extraction of a JSON error body's ``detail`` field.

    Args:
        response: An HTTP response that may or may not carry a JSON body
            shaped like FastAPI's ``HTTPException`` (``{"detail": "..."}"``).

    Returns:
        str | None: The `detail` string, or ``None`` if the body was not
        JSON, was not an object, or had no `detail` key.

    """
    return _response_field(response, "detail")


def _confirm_proposal(proposal_id: str, customer_id: int) -> ConfirmOutcome:
    """Confirm a pending proposal.

    Args:
        proposal_id: Proposal to confirm.
        customer_id: Guest confirming it.

    Returns:
        ConfirmOutcome: What happened, and whether the confirmation dialog
        should stay open for a retry.

    """
    try:
        response = httpx2.post(
            f"{_API_BASE}/v1/booking/confirm",
            json={"proposal_id": proposal_id, "customer_id": customer_id},
            timeout=_CHAT_TIMEOUT_S,
        )
    except Exception as exc:  # noqa: BLE001
        _log_api_failure(
            exc, "Could not reach the API to confirm proposal_id=%s.", proposal_id,
        )
        return ConfirmOutcome(
            status="unreachable",
            message=(
                "Could not reach the booking system. Your request is still "
                "pending — try Confirm again."
            ),
            keep_pending=True,
        )

    if response.status_code == _HTTP_OK:
        return ConfirmOutcome(
            status="confirmed", message=response.json()["message"], keep_pending=False,
        )

    if response.status_code not in _CONFIRM_STATUS_BY_HTTP_CODE:
        # The mapped statuses are logged by the API; this one was not
        # expected, and the guest is told it is safe to try again.
        logger.warning(
            "Confirm of proposal_id=%s returned unexpected HTTP %s.",
            proposal_id,
            response.status_code,
        )
    status = _CONFIRM_STATUS_BY_HTTP_CODE.get(response.status_code, "unreachable")
    detail = _response_detail(response)
    if status in ("unavailable", "unreachable"):
        return ConfirmOutcome(
            status=status,
            message=detail or (
                "The booking system is temporarily unavailable. Your "
                "request is still pending — try Confirm again."
            ),
            keep_pending=True,
        )
    return ConfirmOutcome(
        status=status,
        message=detail or "Could not confirm this request.",
        keep_pending=False,
    )


def _dismiss_proposal(proposal_id: str, customer_id: int) -> None:
    """Dismiss a pending proposal, best-effort.

    A failure to reach the API is logged and otherwise ignored: the
    proposal's own server-side TTL is the backstop, and the caller has
    already dropped it from local state either way. An error status is not
    logged, since a 404 for a proposal the server already invalidated on the
    guest's next message is the normal case.

    Args:
        proposal_id: Proposal to dismiss.
        customer_id: Guest dismissing it.

    """
    try:
        httpx2.post(
            f"{_API_BASE}/v1/booking/dismiss",
            json={"proposal_id": proposal_id, "customer_id": customer_id},
            timeout=_HEALTH_TIMEOUT_S,
        )
    except Exception as exc:  # noqa: BLE001
        _log_api_failure(exc, "Could not dismiss proposal_id=%s.", proposal_id)


def _dismiss_pending_proposal() -> None:
    """Dismiss and clear any proposal left pending in session state."""
    proposal = st.session_state.get("pending_proposal")
    if proposal is None:
        return
    customer_id = st.session_state.get("customer_id")
    if customer_id is not None:
        _dismiss_proposal(proposal["proposal_id"], customer_id)
    st.session_state.pending_proposal = None


# ============================
# Guest claim registry
# ============================
#
# The whole HuggingFace Space runs as one Streamlit process (see
# deploy/supervisord.conf), and every browser session lives inside it as a
# thread of that same process, so a plain module-level dict guarded by a
# lock is enough to keep concurrent sessions off each other's guest --
# no database table or backend endpoint required. It resets if the process
# restarts, which is fine: that clears every session's UI state too.


@dataclasses.dataclass
class _GuestClaim:
    """One guest's exclusive claim by a live session.

    Attributes:
        session_id: Opaque id of the Streamlit session holding the guest.
        last_seen: UTC timestamp of the claim holder's most recent activity.

    """

    session_id: str
    last_seen: datetime


_guest_claims: dict[int, _GuestClaim] = {}
_guest_claims_lock = threading.Lock()


def _try_claim_guest(session_id: str, candidate_ids: list[int]) -> int | None:
    """Claim a random unclaimed guest for a session that has none yet.

    Sweeps out any claims that have gone stale before computing availability,
    so a guest whose previous session vanished without a clean release comes
    back into rotation instead of staying reserved forever.

    Args:
        session_id: Session id to record as the new claim's holder.
        candidate_ids: All seeded guest ids to choose among.

    Returns:
        int | None: The claimed guest's id, or ``None`` if every guest is
        currently claimed by a live session.

    """
    with _guest_claims_lock:
        _sweep_expired_claims_locked()
        available = [cid for cid in candidate_ids if cid not in _guest_claims]
        if not available:
            return None
        chosen = secrets.choice(available)
        _guest_claims[chosen] = _GuestClaim(
            session_id=session_id,
            last_seen=datetime.now(UTC),
        )
        return chosen


def _sweep_expired_claims_locked() -> None:
    """Drop claims idle past `_GUEST_CLAIM_TTL_S`.

    Callers must hold `_guest_claims_lock`.

    """
    cutoff = datetime.now(UTC) - timedelta(seconds=_GUEST_CLAIM_TTL_S)
    expired = [cid for cid, claim in _guest_claims.items() if claim.last_seen < cutoff]
    for cid in expired:
        del _guest_claims[cid]


def _touch_claim(customer_id: int, session_id: str) -> int | None:
    """Refresh a held claim's activity timestamp, or release it if it's lost.

    Recreates the claim if it is missing -- e.g. after a process restart
    cleared the registry, or after a hard refresh restored `customer_id`
    from the URL -- so a session that still holds this guest does not lose
    it on the next claim attempt. If another session's claim has taken over
    this guest in the meantime (its TTL lapsed and it was reassigned before
    this session got back to it), the guest is no longer ours to touch:
    this returns `None` instead of stealing it back.

    Args:
        customer_id: Guest whose claim to refresh.
        session_id: Id of the session asking to hold the claim.

    Returns:
        int | None: `customer_id` if the claim is (still) held by
        `session_id`, `None` if another session now holds it.

    """
    with _guest_claims_lock:
        claim = _guest_claims.get(customer_id)
        if claim is not None and claim.session_id != session_id:
            return None
        _guest_claims[customer_id] = _GuestClaim(
            session_id=session_id,
            last_seen=datetime.now(UTC),
        )
        return customer_id


def _release_claim(customer_id: int | None) -> None:
    """Release a held claim immediately, e.g. on an intentional sign-out.

    Args:
        customer_id: Guest to release, or ``None`` to no-op (nothing to do
            for a session that never claimed a guest).

    """
    if customer_id is None:
        return
    with _guest_claims_lock:
        _guest_claims.pop(customer_id, None)


def _persist_guest_identity(customer_id: int) -> None:
    """Write the session and guest ids into the URL query params.

    Lets the next `_init_session_state()` call -- after a hard refresh --
    restore the same guest claim instead of claiming a fresh one, since
    `st.session_state` does not survive a refresh but the URL does.

    Args:
        customer_id: Guest id currently held by this session.

    """
    st.query_params["sid"] = st.session_state.session_id
    st.query_params["cid"] = str(customer_id)


# ============================
# Rendering
# ============================


@st.fragment(run_every=_HEALTH_POLL_ONLINE_INTERVAL_S)
def _render_online_poll() -> None:
    """Silently poll the API and trigger a full app rerun if it goes offline.

    Registered only while the API is online. Streamlit removes the fragment
    from the render tree on the next full rerun (when the API is down), so
    polling stops automatically once the chatbot goes offline.
    """
    if not _check_health():
        st.rerun()


@st.fragment(run_every=_HEALTH_POLL_OFFLINE_INTERVAL_S)
def _render_recovery_poll() -> None:
    """Silently poll the API and trigger a full app rerun when it recovers.

    Registered only while the API is offline. Streamlit removes the fragment
    from the render tree on the next full rerun (when the API is back), so
    polling stops automatically once the chatbot comes online.
    """
    if _check_health():
        st.rerun()


def _render_login_page() -> None:
    """Render the sign-in page shown to unauthenticated visitors."""
    st.info("Please sign in with your Google account to access the concierge.")
    st.button(
        "Sign in with Google",
        on_click=st.login,
        use_container_width=True,
    )


def _render_guest_assignment() -> None:
    """Claim an exclusive guest for the session, or show why none is held.

    A session with no guest yet claims a random one nobody else currently
    holds, so concurrent visitors to the shared deployment never land on the
    same guest and collide over their reservations. A session that already
    holds a claim -- including one just restored from the URL after a hard
    refresh -- has its activity timestamp refreshed here, so an
    idle-but-connected tab does not lose its seat before
    `_GUEST_CLAIM_TTL_S` actually elapses. A claim restored from the URL
    that turns out to belong to someone else now (this session's earlier
    claim expired and was reassigned before it came back) falls through to
    claiming a fresh guest instead of stealing it back. If every seeded
    guest is claimed, this shows a capacity message instead and leaves
    `customer_id` unset, which the chat input is disabled on.
    """
    customer_id = st.session_state.customer_id
    if customer_id is not None:
        customer_id = _touch_claim(customer_id, st.session_state.session_id)
        st.session_state.customer_id = customer_id

    customers = _fetch_customers()
    if not customers:
        st.warning("Could not load the guest list.")
        return

    if customer_id is None:
        customer_id = _try_claim_guest(
            st.session_state.session_id,
            [c["customer_id"] for c in customers],
        )
        if customer_id is None:
            st.warning(
                "We're at capacity right now. Please check back in a few minutes.",
            )
            return
        st.session_state.customer_id = customer_id

    guest = next((c for c in customers if c["customer_id"] == customer_id), None)
    if guest is None:
        # The guest list changed under us (e.g. a demo database reset) --
        # release the now-stale claim and let the next rerun claim a fresh
        # guest instead of showing a ghost id.
        _release_claim(customer_id)
        st.session_state.customer_id = None
        return

    _persist_guest_identity(customer_id)
    st.caption(f"You're browsing as **{guest['first_name']} {guest['last_name']}**")


def _render_reservations() -> None:
    """Render the "Your reservations" sidebar panel for the current guest.

    Built strictly from `GET /v1/bookings`, never from chat text -- the same
    rule the confirmation dialog follows, and for the same reason: a receipt
    the guest cannot go back and check is barely a receipt. Cancelled
    bookings are left out; a guest can still ask the chat about those.
    """
    st.subheader("Your reservations")
    customer_id = st.session_state.customer_id
    if customer_id is None:
        return

    raw_bookings = _fetch_bookings(customer_id)
    if raw_bookings is None:
        st.caption("Could not load your reservations right now.")
        return

    bookings = [b for b in raw_bookings if b["status"] != "cancelled"]
    if not bookings:
        st.caption("No reservations yet.")
        return

    for booking in bookings:
        label = booking["confirmation_number"] or f"Booking {booking['booking_id']}"
        with st.container(border=True):
            st.markdown(f"**{label}** ({booking['status']})")
            for room in booking["rooms"]:
                st.caption(
                    f"Room {room['room_number']}: {room['check_in']} → "
                    f"{room['check_out']} — ${room['total_amount']}",
                )
            if booking["rooms"]:
                st.caption(f"Total: ${booking['total_amount']}")


def _handle_sign_out() -> None:
    """Release the session's guest claim, then sign the user out.

    A sign-out is a deliberate disconnect, so the claim is freed immediately
    rather than left to expire via `_GUEST_CLAIM_TTL_S`. Also drops the
    `sid`/`cid` query params, so signing back in claims a fresh guest
    instead of the URL silently reattaching the one just released.
    """
    _release_claim(st.session_state.customer_id)
    st.session_state.customer_id = None
    for param in ("sid", "cid"):
        if param in st.query_params:
            del st.query_params[param]
    st.logout()


def _render_sidebar() -> None:
    """Render the sidebar: auth info, guest assignment, health, and controls."""
    with st.sidebar:
        st.header("Blue Horizon")

        if _AUTH_ENABLED:
            st.caption(f"Signed in as **{st.user.name or st.user.email}**")
            st.button("Sign out", on_click=_handle_sign_out, use_container_width=True)
            st.divider()

        _render_guest_assignment()
        st.divider()

        # Published to session state so _render_pending_resend() (rendered
        # later, in _render_chat()) can gate "Send again" on it without a
        # second /v1/health round trip of its own.
        online = _check_health()
        st.session_state.api_online = online
        # This reports readiness (`/v1/health`: startup finished), not
        # whether the model provider, Redis, or Postgres are reachable right
        # now; a failure during a turn shows up in the chat's own failure
        # block instead. Hence "Running", which it can honestly claim.
        if online:
            st.success("Service: Running")
            _render_online_poll()
        else:
            st.error("Service: Unavailable")
            _render_recovery_poll()

        st.divider()

        if st.button("New Conversation", use_container_width=True):
            _reset_session()
            st.rerun()

        st.divider()
        _render_reservations()


def _md(text: str) -> None:
    """Render text as Markdown with dollar signs escaped to prevent LaTeX parsing.

    Args:
        text: Text to render as Markdown.

    """
    st.markdown(text.replace("$", r"\$"))


def _parse_sse_line(line: str) -> dict[str, Any] | None:
    """Parse one line of an SSE stream into its JSON event payload.

    Args:
        line: One line read from the response body.

    Returns:
        dict[str, Any] | None: The decoded event, or ``None`` for lines that
        are not a ``data: `` event or fail to decode (e.g. a keepalive
        comment line).

    """
    if not line.startswith("data: "):
        return None
    try:
        return json.loads(line[6:])
    except json.JSONDecodeError:
        return None


@dataclasses.dataclass(frozen=True, slots=True)
class ChatTurnResult:
    """Outcome of one `_stream_message` call.

    Attributes:
        ok: Whether the assistant actually produced a reply. False for
            every failure this module can classify -- an `error` SSE event,
            a non-2xx HTTP response, a timeout, or an unreachable API --
            since none of those means the turn is safe to treat as answered.
            These are Tier B failures in the failure-handling tiering: the
            system never auto-retries a chat turn server-side (it may
            already have mutated the proposal store or the conversation
            checkpoint, and it always consumes LLM tokens), but a
            guest-initiated resend of the exact same text is always safe,
            which is what `_render_pending_resend` offers when `ok` is
            False.
        text: The assistant's reply on success, or guest-facing failure copy
            on failure. Never raw exception text either way.
        proposal: A pending proposal dict, if the turn created one. Always
            `None` when `ok` is False.

    """

    ok: bool
    text: str
    proposal: dict[str, Any] | None


def _handle_stream_event(
    event: dict[str, Any],
    status: DeltaGenerator,
    pending_proposal: dict[str, Any] | None,
) -> tuple[dict[str, Any] | None, ChatTurnResult | None]:
    """Apply one SSE event to the status widget.

    Args:
        event: Decoded SSE event.
        status: The turn's `st.status` widget.
        pending_proposal: Proposal captured from an earlier event this turn,
            if any.

    Returns:
        tuple: `(pending_proposal, result)`. `pending_proposal` carries
        forward to the next event; `result` is non-``None`` exactly when the
        caller should return it immediately (an `error` or `done` event ends
        the turn).

    """
    event_type = event.get("type")
    if event_type == "stage":
        status.update(label=event["label"], state="running")
    elif event_type == "error":
        status.update(label="Error", state="error")
        message = str(event.get("message", "Something went wrong."))
        return pending_proposal, ChatTurnResult(ok=False, text=message, proposal=None)
    elif event_type == "done":
        status.update(label="Done", state="complete")
        response_text = str(event.get("response", "No response received."))
        return pending_proposal, ChatTurnResult(
            ok=True, text=response_text, proposal=pending_proposal,
        )
    elif event_type == "proposal":
        # `.get()`, not indexing: a malformed event must not crash the turn
        # with a bare KeyError that the generic exception handler below
        # would otherwise report as an unhelpful "Could not reach the API".
        proposal_id = event.get("proposal_id")
        action = event.get("action")
        summary = event.get("summary")
        if proposal_id is None or action is None or summary is None:
            logger.warning("Malformed proposal event, ignoring: %r", event)
        else:
            pending_proposal = {
                "proposal_id": proposal_id,
                "action": action,
                "summary": summary,
            }
    return pending_proposal, None


def _stream_message(thread_id: str, customer_id: int, text: str) -> ChatTurnResult:
    """Stream a chat turn from the unified endpoint and display live progress.

    Connects to ``POST /v1/chat`` with ``Accept: text/event-stream`` and
    updates a :func:`streamlit.status` widget as each event arrives.

    This function must be called inside a ``st.chat_message`` context so that
    the status widget is rendered inside the assistant bubble.

    Args:
        thread_id: Unique identifier for the current conversation thread.
        customer_id: The current guest, bound to `thread_id` on first use.
        text: The user's message text.

    Returns:
        ChatTurnResult: The assistant's reply, or a failure the guest can
        retry with "Send again".

    """
    status = st.status("Routing your request…", state="running")
    pending_proposal: dict[str, Any] | None = None
    try:
        with httpx2.stream(
            "POST",
            f"{_API_BASE}/v1/chat",
            json={"thread_id": thread_id, "customer_id": customer_id, "text": text},
            headers={"Accept": "text/event-stream"},
            timeout=_CHAT_TIMEOUT_S,
        ) as response:
            response.raise_for_status()
            for line in response.iter_lines():
                event = _parse_sse_line(line)
                if event is None:
                    continue
                pending_proposal, result = _handle_stream_event(
                    event, status, pending_proposal,
                )
                if result is not None:
                    return result
    except httpx2.HTTPStatusError as exc:
        _log_api_failure(exc, "Chat request for thread_id=%s failed.", thread_id)
        error_message = _http_error_message(exc)
    # None of the failure copy below tells the guest to try again: it is
    # rendered above the "Send again" button, which is that instruction.
    except httpx2.TimeoutException as exc:
        # Logged here only: the API may still be running the turn.
        _log_api_failure(exc, "Chat request for thread_id=%s timed out.", thread_id)
        error_message = "The concierge took too long to reply."
    except Exception as exc:  # noqa: BLE001
        _log_api_failure(exc, "Chat request for thread_id=%s failed.", thread_id)
        error_message = "Could not reach the concierge."
    else:
        return ChatTurnResult(
            ok=True, text="No response received.", proposal=pending_proposal,
        )

    status.update(label="Error", state="error")
    return ChatTurnResult(ok=False, text=error_message, proposal=None)


def _http_error_message(exc: httpx2.HTTPStatusError) -> str:
    """Translate a chat-endpoint HTTP error into user-facing copy.

    Args:
        exc: HTTP status error raised by the chat request.

    Returns:
        str: User-facing error message.

    """
    if exc.response.status_code == _HTTP_SERVICE_UNAVAILABLE:
        # The readiness gate's own body carries `message`, already picked
        # between "still starting up" and "won't resolve on its own" server
        # side -- see api.app._not_ready_response. The fallback only fires
        # if that body could not be parsed at all.
        message = _response_field(exc.response, "message")
        return message or "The concierge is still starting up."
    return (
        f"Something went wrong on our side (error {exc.response.status_code})."
    )


def _render_book_summary(summary: dict[str, Any]) -> None:
    """Render a `book` proposal's line items inside the confirmation dialog.

    Args:
        summary: Proposal summary with a `rooms` list and a `total`.

    """
    for room in summary["rooms"]:
        st.write(
            f"Room {room['room_number']}: {room['check_in']} → {room['check_out']} "
            f"({room['nights']} nights) — ${room['amount']}",
        )
    st.markdown(f"**Total: ${summary['total']}**")


def _render_cancel_summary(summary: dict[str, Any]) -> None:
    """Render a `cancel` proposal's line items inside the confirmation dialog.

    Args:
        summary: Proposal summary with a `rooms` list and a refund `total`.

    """
    for room in summary["rooms"]:
        st.write(f"Room {room['room_number']}: refund ${room['amount']}")
    st.markdown(f"**Total refund: ${summary['total']}**")


def _render_modify_summary(summary: dict[str, Any]) -> None:
    """Render a `modify` proposal's before/after changes inside the dialog.

    Args:
        summary: Proposal summary with a `changes` list and a new `total`.

    """
    for change in summary["changes"]:
        before, after = change["before"], change["after"]
        st.write(
            f"Room {before['room_number']} ({before['check_in']} → "
            f"{before['check_out']}) **becomes** Room {after['room_number']} "
            f"({after['check_in']} → {after['check_out']})",
        )
    st.markdown(f"**New total: ${summary['total']}**")


_SUMMARY_RENDERERS = {
    "book": _render_book_summary,
    "cancel": _render_cancel_summary,
    "modify": _render_modify_summary,
}

# Shown instead of a "refused" outcome's own detail when this confirm
# attempt followed one that came back "unavailable" or "unreachable" on the
# same proposal. In that situation the earlier write may have already
# landed with its acknowledgement lost, so asserting the nights were taken
# by someone else would tell the guest the opposite of the truth.
_AMBIGUOUS_REFUSAL_MSG = (
    "We could not confirm whether this went through. Please check "
    '"Your reservations" before trying again.'
)


@st.dialog("Review your request", dismissible=False)
def _render_proposal_dialog(proposal: dict[str, Any]) -> None:
    """Render the confirmation dialog for a pending proposal.

    Built strictly from `proposal["summary"]` -- resolved, priced line items
    computed by the application -- and never from assistant chat text. This
    is the load-bearing detail from the design this UI implements: the
    dialog and the eventual commit must never be able to disagree, so do not
    "simplify" this to reuse the assistant's message text instead.

    Not dismissible, so Confirm and Cancel are the only ways out. A click
    outside the dialog, ESC, or its X would close it in the browser only:
    `pending_proposal` stays set and the proposal stays pending on the
    server, so the dialog would reappear on the guest's next unrelated
    interaction, such as switching guests in the sidebar.

    A confirm that comes back `unavailable` or `unreachable` (see
    `ConfirmOutcome`) leaves the dialog open with Confirm still enabled
    instead of closing it: the write was never evaluated, so pressing
    Confirm again is a clean retry, not a duplicate booking attempt.

    Args:
        proposal: Pending proposal dict with `proposal_id`, `action`,
            `summary`, and (once a retry-safe failure has occurred)
            `had_operational_failure`.

    """
    renderer = _SUMMARY_RENDERERS[proposal["action"]]
    renderer(proposal["summary"])

    col_confirm, col_cancel = st.columns(2)
    if col_confirm.button("Confirm", type="primary", use_container_width=True):
        customer_id = st.session_state.customer_id
        # Set by an earlier attempt on this same proposal that came back
        # "unavailable" or "unreachable" -- see the branch below. Tracked so
        # a "refused" outcome on *this* attempt can be recognised as the
        # lost-acknowledgement case: the earlier write may have actually
        # landed, so this retry's refusal does not necessarily mean the
        # nights were taken by someone else. Step 18 (reconciliation) is the
        # real fix; this is the interim mitigation described in the plan.
        had_operational_failure = proposal.get("had_operational_failure", False)
        outcome = _confirm_proposal(proposal["proposal_id"], customer_id)

        if outcome.keep_pending:
            proposal["had_operational_failure"] = True
            st.session_state.pending_proposal = proposal
            st.warning(outcome.message)
        else:
            message = _AMBIGUOUS_REFUSAL_MSG if (
                outcome.status == "refused" and had_operational_failure
            ) else outcome.message
            st.session_state.pending_proposal = None
            st.session_state.messages.append({"role": "assistant", "content": message})
            st.rerun()

    if col_cancel.button("Cancel", use_container_width=True):
        customer_id = st.session_state.customer_id
        _dismiss_proposal(proposal["proposal_id"], customer_id)
        st.session_state.pending_proposal = None
        st.rerun()


def _submit_chat_message(prompt: str) -> None:
    """Send one chat turn and fold the outcome into session state.

    On success, appends the assistant's reply to history and stores any
    pending proposal. On failure, the guest's own message (already in
    history by the time this is called) is left standing alone -- nothing
    is fabricated to look like an assistant reply -- and the text plus
    failure copy are stashed for `_render_pending_resend` instead.

    Must be called inside a ``st.chat_message("assistant")`` context so a
    successful reply renders inside the assistant bubble.

    Args:
        prompt: The guest's message text for this turn.

    """
    result = _stream_message(
        st.session_state.thread_id, st.session_state.customer_id, prompt,
    )
    if result.ok:
        _md(result.text)
        st.session_state.messages.append(
            {"role": "assistant", "content": result.text},
        )
        st.session_state.pending_proposal = result.proposal
        st.session_state.pending_resend = None
        st.session_state.pending_resend_message = None
    else:
        st.session_state.pending_resend = prompt
        st.session_state.pending_resend_message = result.text


def _render_pending_resend() -> None:
    """Render the system-state block for a chat turn that failed to complete.

    Shown as its own block rather than an assistant bubble, since nothing
    was actually said -- the guest's own message stays in history as-is,
    and this is what offers the resend instead of a bare "try again"
    sentence. "Send again" replays the exact same text and stays disabled
    until `_render_sidebar` observes the API healthy again, wiring the
    already-existing recovery poll to this control for the first time.
    """
    prompt = st.session_state.pending_resend
    if prompt is None:
        return
    st.warning(st.session_state.pending_resend_message)
    online = st.session_state.api_online
    if st.button("Send again", disabled=not online, use_container_width=True):
        with st.chat_message("assistant"):
            _submit_chat_message(prompt)
        st.rerun()
    if not online:
        st.caption("Send again will be available once the service is back.")


def _render_chat() -> None:
    """Render the chat message history, pending proposal, and new user input."""
    for msg in st.session_state.messages:
        with st.chat_message(msg["role"]):
            _md(msg["content"])

    _render_pending_resend()

    if st.session_state.pending_proposal is not None:
        _render_proposal_dialog(st.session_state.pending_proposal)

    placeholder = "Ask about the hotel, or get help searching or booking rooms..."
    if prompt := st.chat_input(
        placeholder, disabled=st.session_state.customer_id is None,
    ):
        _dismiss_pending_proposal()
        # A new message supersedes any resend still offered for an earlier,
        # failed one -- typing past it means the guest has moved on.
        st.session_state.pending_resend = None
        st.session_state.pending_resend_message = None

        st.session_state.messages.append({"role": "user", "content": prompt})
        with st.chat_message("user"):
            _md(prompt)

        with st.chat_message("assistant"):
            _submit_chat_message(prompt)
        st.rerun()


# ============================
# Entry point
# ============================


def main() -> None:
    """Configure logging and the Streamlit page, and render all UI components."""
    # A no-op on every rerun after the first, once the root logger has a
    # handler. Called here rather than at import so tests importing this
    # module leave logging alone.
    logging.basicConfig(level=logging.INFO, format=_LOG_FORMAT)
    st.set_page_config(
        page_title="Blue Horizon Concierge",
        page_icon="🏨",
        layout="centered",
    )
    st.title("Blue Horizon Concierge 🌅")
    st.subheader("AI concierge to help with room bookings and answer questions about "
                 "the hotel and its services/amenities")

    if _AUTH_ENABLED and not st.user.is_logged_in:
        _render_login_page()
        st.stop()

    _init_session_state()
    _render_sidebar()
    _render_chat()


if __name__ == "__main__":
    main()
